### PR TITLE
removed seed getting from CoreRegistry and implemented method setWorldSeed()

### PR DESCRIPTION
**Pull request by 0shine0**
for pr 2815 in MovingBlocks/Terasology.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks!

Watch out for tab characters, those snuck in here instead of 4 spaces. There should be config in your IDE to favor spaces over tabs :-)

Like I noted over in https://github.com/Terasology/WoodAndStone/issues/47 this does break another world gen in WoodCrafting so we need something fixed up before merging. Feel free to fix the tabs -> spaces here if you get a chance or end up applying more tweaks anyway.

**Comment by 0shine0** [comment]
@Cervator Replaced tabs with spaces :)

**Comment by 0shine0** [comment]
@cervator merge this pr as well as the ones in woodCrafting and wood and stone modules if they work.

**Comment by xrtariq2594** [comment]
Good work!

**Pull request merged**
